"""Add PracticeAttempt model

Revision ID: 961f424dc45d
Revises: b4cb3fffa323
Create Date: 2026-05-30 21:44:39.618306
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '961f424dc45d'
down_revision: Union[str, Sequence[str], None] = 'b4cb3fffa323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('character', sa.String(length=4), nullable=False),
    sa.Column('mistakes', sa.SmallInteger(), nullable=False),
    sa.Column('is_perfect', sa.Boolean(), nullable=False),
    sa.Column('practiced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_attempts_character'), 'practice_attempts', ['character'], unique=False)
    op.create_index(op.f('ix_practice_attempts_practiced_at'), 'practice_attempts', ['practiced_at'], unique=False)
    op.create_index(op.f('ix_practice_attempts_user_id'), 'practice_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_attempts_user_id'), table_name='practice_attempts')
    op.drop_index(op.f('ix_practice_attempts_practiced_at'), table_name='practice_attempts')
    op.drop_index(op.f('ix_practice_attempts_character'), table_name='practice_attempts')
    op.drop_table('practice_attempts')
    # ### end Alembic commands ###
