"""Add practice fields

Revision ID: b4cb3fffa323
Revises: 20260527_0001
Create Date: 2026-05-30 21:13:05.537975
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4cb3fffa323'
down_revision: Union[str, Sequence[str], None] = '20260527_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hanzi_characters', sa.Column('stroke_count', sa.SmallInteger(), nullable=True))
    op.add_column('hanzi_characters', sa.Column('topic', sa.String(length=100), nullable=True))
    op.add_column('hanzi_characters', sa.Column('radicals', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('hanzi_characters', sa.Column('etymology_vi', sa.Text(), nullable=True))
    op.add_column('hanzi_characters', sa.Column('audio_url', sa.Text(), nullable=True))
    op.add_column('hanzi_characters', sa.Column('stroke_svg', sa.Text(), nullable=True))
    op.create_index(op.f('ix_hanzi_characters_topic'), 'hanzi_characters', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hanzi_characters_topic'), table_name='hanzi_characters')
    op.drop_column('hanzi_characters', 'stroke_svg')
    op.drop_column('hanzi_characters', 'audio_url')
    op.drop_column('hanzi_characters', 'etymology_vi')
    op.drop_column('hanzi_characters', 'radicals')
    op.drop_column('hanzi_characters', 'topic')
    op.drop_column('hanzi_characters', 'stroke_count')
    # ### end Alembic commands ###
